POST http://localhost:8080/api/auth/register.php
Content-Type: application/json

{
    "name":"Mark",
    "password":"111222333",
    "email":"mark@email.com",
    "first_name":"Rollie",
    "last_name":"Garcia"
}

### user login

POST http://localhost:8080/api/auth/login.php
Content-Type: application/json

{
    "email":"mark@email.com",
    "password":"111222333"
}

### logout

POST http://localhost:8080/api/auth/logout.php
Content-Type: application/json

### get user info
GET http://localhost:8080/api/auth/me.php
Content-Type: application/json

### create role
POST http://localhost:8080/api/role/create.php
Content-Type: application/json

{
    "name":"fucker"
}

### update roles
POST http://localhost:8080/api/user/update.php
Content-Type: application/json

{
    "role":"admin"
}

### create group
POST http://localhost:8080/api/groups/create.php
Content-Type: application/json

{
    "name":"BS-CPE 1A",
    "description":"test description"
}